backend:
  name: git-gateway
  branch: master 
media_folder: "/media"  
collections:
  - name: "text" 
    label: "text" 
    folder: "content/text" 
    create: true 
    fields:
      - {label: "Key", name: "title", widget: "string"}
      - {label: "Português", name: "pt", widget: "markdown"}
      - {label: "Inglês", name: "en", widget: "markdown"}
  
  - name: "terms"    
    label: "terms" 
    folder: "content/terms" 
    create: true 
    fields: 
      - {label: "Key", name: "title", widget: "string"}
      - {label: "Português", name: "pt", widget: "string"}
      - {label: "Inglês", name: "en", widget: "string"}
   